### ISSUE TITLE
Differences between FreiHAND and HanCo

### ISSUE THREAD

**Issue by hxwork** [lmb-freiburg/contra-hand#13]
Hi,

Thanks for creating and releasing such an awesome dataset! When reading the paper, I am confused about the differences between the FreiHAND dataset and the HanCo dataset. There are some questions,

(1) Does the annotated data the same? In other words, I would like to know if the annotated multi-view images used for training in the HanCo dataset are the same as the training set of the FreiHAND (before background augmentation).
(2) Is there any overlapping data between the evaluation set of the FreiHAND dataset and the released HanCo dataset?
(3) What is the train/test split of the HanCo dataset? Is it reasonable to use the HanCo dataset to train the model and test it on the FreiHAND evaluation set?

Hope you can help me solve these confusions. Many thanks!

Best,
Hao XU

**Comment by zimmerm** [comment]
> (1) Does the annotated data the same? In other words, I would like to know if the annotated multi-view images used for training in the HanCo dataset are the same as the training set of the FreiHAND (before background augmentation).

Yes there is overlap and no there is no mapping to identify the 'same' frames in each of the datasets. However the separation between train/validation is clean.

> (2) Is there any overlapping data between the evaluation set of the FreiHAND dataset and the released HanCo dataset?

Yes there is overlap and no there is no mapping to identify the 'same' frames in each of the datasets.  However the separation between train/validation is clean.

> (3) What is the train/test split of the HanCo dataset? Is it reasonable to use the HanCo dataset to train the model and test it on the FreiHAND evaluation set?
Yes that should be perfectly fine.
