### ISSUE TITLE
mano shape annotation

### ISSUE THREAD

**Issue by hongsukchoi** [lmb-freiburg/contra-hand#14]
Many thanks to this great dataset.

I have a question about the 'mano shape' annotation. The shape annotation folder has world mano shape annotation and also has shape annotation for each camera. I was curious why the authors provided the shape for each camera and searched into the code here. I found [this line](https://github.com/lmb-freiburg/contra-hand/blob/cddbad25f5661fb9ee32849af990e2b207d235e0/show_dataset.py#L124). If I understand correctly, is the shape annotation for each camera actually from an off-the-shelf estimator? not the annotation?

**Comment by hongsukchoi** [comment]
Also, I found that joints from the mano parameters and joints from 'xyz' directory are different. What are the relationship between them?

**Comment by zimmerm** [comment]
> The shape annotation folder has world mano shape annotation and also has shape annotation for each camera.
AFAIK they should be the same, up to the global translation and rotation. They are available both just for convenience. If you compare they will have the same shape and pose parameters.

> Also, I found that joints from the mano parameters and joints from 'xyz' directory are different. What are the relationship between them?
xyz is what the joint MVnet of the FreiHAND paper provided and what is used as one of the objectives for shape optimisation.
