### ISSUE TITLE
Link to the random background images is broken

### ISSUE THREAD

**Issue by shlokk** [lmb-freiburg/contra-hand#3]
Hi, 
Then link to Random Background Images is broken(https://lmb.informatik.uni-freiburg.de/resources/datasets/HanCo_bg.zip ). Can you guys fix the link?

**Comment by shlokk** [comment]
Please provide us with any updates on this, even if you guys can give us the image ID's that would be sufficient for us.

**Comment by BlGene** [comment]
Hi, 

#4 should fix your problem. Please let me know if it dose not.

BR, Max

**Comment by shlokk** [comment]
Thanks for the dataset.
