### ISSUE TITLE
Misaligned 3D keypoints and hand mesh result 

### ISSUE THREAD

**Issue by janojoshua** [lmb-freiburg/contra-hand#5]
This is a really great job.
I just downloaded the dataset and tried to visualize it. 
After that, i found there was something wrong here.
First, when i tried to run 'rgb/000/cam0/', everything was fine both projected keypoint and mesh aligned well.
![00000000](https://user-images.githubusercontent.com/95740599/147548345-843a30d9-299a-4617-bed6-b2f6996f0308.jpg)
![00000000](https://user-images.githubusercontent.com/95740599/147548371-9b268581-fc12-4fd8-8f5c-6c0987434b8f.jpg)
But when i run for 'rgb/000/cam1/' and so on the result are not aligned.
![00000038](https://user-images.githubusercontent.com/95740599/147548758-ad1c6756-5630-4a91-8a50-f9df46286847.jpg)
![00000038](https://user-images.githubusercontent.com/95740599/147548779-4f06449a-0d8c-4164-bfef-c2e4dd30ef72.jpg)
When i checked the code, i found that i used the correct K index. Is it because the data problem or is it just my mistake?. 
Sorry for taking your time. Thank you for your attention.

**Comment by He-Chao** [comment]
Hi, I downloaded the dataset and tried to visualize it. But I can not visualize image with mesh just 3d keypoint. Can you tell me how you do it?

**Comment by zimmerm** [comment]
I'd recommend you use the visualization tools that are used in the `show_dataset.py` script in this repository. If there are issues with using this script feel free to open another issue.
