### ISSUE TITLE
Clarification on checkpoints

### ISSUE THREAD

**Issue by andreaziani** [lmb-freiburg/contra-hand#7]
Hi, 
First of all, thank you for this great work and dataset! I truly believe that this will help the community exploring semi/self-supervised approaches for HPE. 

I have a question related to the released checkpoints, which contrastive approach has been used to produce `contra-hand-ckpt/ckpt/model_moco.pth` ? Is this the multi-view approach described in the paper? 
Also, would it be possible to release the checkpoints for all contrastive trainings mentioned in the paper?  

Thanks in advance,
Andrea

**Comment by zimmerm** [comment]
Hi
you are exactly right _model_moco.pth_ is what we refer to as _Ours-Multi view_ in Table 1 of our paper. 
It would require some digging in our internal codebase but theoretically that is possible. What are you planning to do with these inferior initialisation checkpoints?

**Comment by andreaziani** [comment]
Hi, thanks for the reply!

I'm working on my Master's Thesis and I was interested in visualizing what are the main differences in terms of qualitative and quantitative results using your different pre-training strategies.

That's why it'd be great having all of the checkpoints 😄
