### ISSUE TITLE
How to evaluate on this dataset?

### ISSUE THREAD

**Issue by fuqichen1998** [lmb-freiburg/contra-hand#8]
As the title, is there an online challenge portal or evaluation script to test our model on this dataset?

**Comment by Lily-Le** [comment]
Same question here :D. I'm working on my Graduation design, and need to compare different methods for pre-training. Is there an evaluation / train script published online?   Thanks a lot.

**Comment by zimmerm** [comment]
There is no separate Codalab portal for this dataset, but you can use the evaluation tooling from here https://github.com/lmb-freiburg/freihand
