### ISSUE TITLE
where is the file "index_mv_unsup_weak.json"

### ISSUE THREAD

**Issue by liwenssss** [lmb-freiburg/contra-hand#9]

**Comment by zimmerm** [comment]
More information is needed:
- Where do you find the reference to this file?
- What is it needed for?

Feel free to open up the issue again.

**Comment by fatbao55** [comment]
I am unable to find the file too. `index_mv_unsup_weak.json` is referenced here https://github.com/lmb-freiburg/contra-hand/blob/cddbad25f5661fb9ee32849af990e2b207d235e0/DatasetUnsupervisedMV.py#L68
